# Generated by Django 5.1.4 on 2025-01-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0002_remove_article_id_remove_rating_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(max_length=300, upload_to='media'),
        ),
    ]
