# Generated by Django 5.1.4 on 2025-01-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0004_category_imagemodel_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='cata.article'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='cata.category'),
        ),
    ]
