# Generated by Django 5.1.4 on 2025-01-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0005_alter_imagemodel_article_alter_imagemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='heading',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
