# Generated by Django 5.1.4 on 2025-01-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0006_alter_article_description_alter_article_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
