# Generated by Django 5.1.4 on 2025-01-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0008_videomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='cata.category'),
        ),
    ]
