# Generated by Django 5.1.4 on 2025-01-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0010_comment'),
    ]

    operations = [
    ]
